{% set name = "gwcosmo" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gwcosmo-{{ version }}.tar.gz
  sha256: d20b8febc7c4dc3b4a2c625aec7916900035a20f85d0012ecfc49ea123f9733b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - astropy-base
    - bilby
    - h5py
    - healpy
    - lalsuite
    - ligo-gracedb
    - ligo-segments
    - ligo.skymap <=1.0.7
    - lscsoft-glue
    - matplotlib-base >=2.0
    - numpy <=1.23.5,>=1.19
    - pandas
    - progressbar
    - scipy
    - seaborn
    - tqdm

test:
  imports:
    - gwcosmo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://lscsoft.docs.ligo.org/gwcosmo/
  summary: A package to estimate cosmological parameters using gravitational-wave observations
  license: GPL-2.0-only
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - transientlunatic
    - CChapmanbird
    - rachelmgray
    - jcbayley
